name: Docker Multi-Architecture Build

on:
    push:
        paths-ignore:
            - "**.md"
        branches:
            - master
    workflow_dispatch:

jobs:
    build-docker:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
          attestations: write
          id-token: write
        steps:
            - uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
              with:
                  platforms: all
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v3
              with:
                  version: latest
            - name: Login to ghcr.io
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  platforms: linux/amd64,linux/arm64/v8
                  push: true
                  tags: ghcr.io/nyanactions/youtube-trusted-session-generator:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
            - name: Build and push with HTTP API
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile.webserver
                  platforms: linux/amd64,linux/arm64/v8
                  push: true
                  tags: ghcr.io/nyanactions/youtube-trusted-session-generator:webserver
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
